name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-coder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build coder package
        run: bun run build
        working-directory: ./app/coder
      
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      
      - name: Publish coder to NPM
        run: npm publish --access public
        working-directory: ./app/coder

  publish-writer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build writer package
        run: bun run build
        working-directory: ./app/writer
      
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      
      - name: Publish writer to NPM
        run: npm publish --access public
        working-directory: ./app/writer